import OBR from "https://cdn.jsdelivr.net/npm/@owlbear-rodeo/sdk@3.1.0/+esm";

const CHANNEL = "cinematic-location-titles/v3";
const THEME_STORAGE_KEY = "cinematic-title:last-theme";
const THEMES = new Set(["morkborg", "lancer", "dnd", "warhammer"]);
const titleEl=document.querySelector("#title"),subtitleEl=document.querySelector("#subtitle"),durationEl=document.querySelector("#duration"),darknessEl=document.querySelector("#darkness"),darknessValueEl=document.querySelector("#darknessValue"),themeEl=document.querySelector("#theme"),themeButtons=[...document.querySelectorAll("[data-theme]")],showBtn=document.querySelector("#show"),hideBtn=document.querySelector("#hide"),statusEl=document.querySelector("#status"),roleNoticeEl=document.querySelector("#roleNotice");
let lastAutoTitle="";
const upper=(v,l=80)=>String(v??"").trim().toLocaleUpperCase("ru-RU").slice(0,l);
const upperTyping=(v,l=80)=>String(v??"").toLocaleUpperCase("ru-RU").slice(0,l);
const cleanItemName=v=>String(v??"").trim().replace(/\.(png|jpe?g|webp|gif|avif|svg|mp4|webm)$/i,"").replace(/[_-]+/g," ").replace(/\s+/g," ").trim();
function metadataSceneName(m){if(!m||typeof m!=="object")return"";for(const k of["sceneName","scene_name","name"])if(typeof m[k]==="string"&&m[k].trim())return m[k].trim();return""}
function getStoredTheme(){try{const s=localStorage.getItem(THEME_STORAGE_KEY);return THEMES.has(s)?s:"morkborg"}catch{return"morkborg"}}
function selectTheme(theme,{persist=true}={}){const t=THEMES.has(theme)?theme:"morkborg";themeEl.value=t;for(const b of themeButtons)b.setAttribute("aria-pressed",String(b.dataset.theme===t));if(persist)try{localStorage.setItem(THEME_STORAGE_KEY,t)}catch{}}
async function detectCurrentSceneTitle(){if(!(await OBR.scene.isReady()))return{title:"",source:"none"};try{const m=await OBR.scene.getMetadata();const n=metadataSceneName(m);if(n)return{title:upper(n),source:"metadata"}}catch(e){console.warn("Scene metadata lookup failed",e)}try{const maps=await OBR.scene.items.getItems(i=>i.layer==="MAP"&&i.type==="IMAGE");if(maps.length){const sorted=[...maps].sort((a,b)=>((b.image?.width||0)*(b.scale?.x||1)*(b.image?.height||0)*(b.scale?.y||1))-((a.image?.width||0)*(a.scale?.x||1)*(a.image?.height||0)*(a.scale?.y||1)));const n=cleanItemName(sorted[0]?.name);if(n)return{title:upper(n),source:"map"}}}catch(e){console.warn("Base-map lookup failed",e)}return{title:"",source:"none"}}
async function refreshAutoTitle({announce=false}={}){const before=upper(titleEl.value),mayReplace=!before||before===lastAutoTitle;if(!mayReplace)return;const d=await detectCurrentSceneTitle();if(!d.title){if(before===lastAutoTitle)titleEl.value="";lastAutoTitle="";if(announce)setStatus("Имя сцены не удалось получить — введите заголовок вручную.");return}titleEl.value=d.title;lastAutoTitle=d.title;if(announce)setStatus(d.source==="metadata"?`Подставлено название: «${d.title}».`:`Подставлено имя основной карты: «${d.title}». Его можно заменить вручную.`,"ok")}
function setStatus(text,kind=""){statusEl.textContent=text;statusEl.className=`status ${kind}`.trim()}
function setControlsEnabled(enabled){for(const el of[titleEl,subtitleEl,durationEl,darknessEl,showBtn,hideBtn,...themeButtons])el.disabled=!enabled}
for(const b of themeButtons)b.addEventListener("click",()=>selectTheme(b.dataset.theme));selectTheme(getStoredTheme(),{persist:false});
for(const [el,limit] of [[titleEl,80],[subtitleEl,120]])el.addEventListener("input",()=>{const s=el.selectionStart,e=el.selectionEnd,t=upperTyping(el.value,limit);if(el.value!==t){el.value=t;try{el.setSelectionRange(s,e)}catch{}}});
darknessEl.addEventListener("input",()=>darknessValueEl.value=`${Math.round(Number(darknessEl.value)*100)}%`);
OBR.onReady(async()=>{try{const role=await OBR.player.getRole();if(role!=="GM"){setControlsEnabled(false);roleNoticeEl.hidden=false;setStatus("Клиент слушает общие титры. Панель управления отключена.");return}setControlsEnabled(true);setStatus("Готово. Ищу название текущей сцены…");await refreshAutoTitle({announce:true});OBR.scene.onReadyChange(async ready=>{if(ready)await refreshAutoTitle({announce:true})});showBtn.addEventListener("click",async()=>{const title=upper(titleEl.value),subtitle=upper(subtitleEl.value,120),duration=Math.max(2200,Math.min(15000,Number(durationEl.value)||5000)),darkness=Math.max(.25,Math.min(.9,Number(darknessEl.value)||.62)),theme=THEMES.has(themeEl.value)?themeEl.value:"morkborg";titleEl.value=title;subtitleEl.value=subtitle;selectTheme(theme);if(!title){setStatus("Введите заголовок локации.","error");titleEl.focus();return}try{await OBR.broadcast.sendMessage(CHANNEL,{type:"SHOW",title,subtitle,duration,darkness,theme,sentAt:Date.now()},{destination:"ALL"});setStatus(`Показ: «${title}» / ${theme.toUpperCase()}`,"ok")}catch(e){console.error(e);setStatus("Не удалось отправить титр. Проверьте подключение комнаты.","error")}});hideBtn.addEventListener("click",async()=>{try{await OBR.broadcast.sendMessage(CHANNEL,{type:"HIDE",sentAt:Date.now()},{destination:"ALL"});setStatus("Заставка скрыта.","ok")}catch(e){console.error(e);setStatus("Не удалось скрыть заставку.","error")}})}catch(e){console.error(e);setControlsEnabled(false);setStatus("Не удалось подключиться к API Owlbear Rodeo.","error")}});
