import OBR from "https://cdn.jsdelivr.net/npm/@owlbear-rodeo/sdk@3.1.0/+esm";
const MODAL_ID="cinematic-location-titles/v3-overlay",THEMES=new Set(["morkborg","lancer","dnd","warhammer"]),params=new URLSearchParams(location.search);
let title=(params.get("title")||"").trim().toLocaleUpperCase("ru-RU").slice(0,80),subtitle=(params.get("subtitle")||"").trim().toLocaleUpperCase("ru-RU").slice(0,120);const duration=Math.max(2200,Math.min(15000,Number(params.get("duration"))||5000)),darkness=Math.max(.25,Math.min(.9,Number(params.get("darkness"))||.62)),requested=params.get("theme")||"morkborg",theme=THEMES.has(requested)?requested:"morkborg";
if(theme==="warhammer"){title=title.replaceAll("Ё","Е");subtitle=subtitle.replaceAll("Ё","Е")}
document.documentElement.style.setProperty("--duration",`${duration}ms`);document.documentElement.style.setProperty("--darkness",String(darkness));
const cinematic=document.querySelector("#cinematic");cinematic.className=`cinematic theme-${theme}`;
function setText(id,value){const el=document.querySelector(id);if(el)el.textContent=value}
setText("#morkTitle",title);setText("#morkSubtitle",subtitle);setText("#lancerTitle",title);setText("#lancerSubtitle",subtitle);document.querySelector("#morkTitle").dataset.title=title;document.querySelector("#lancerTitle").dataset.title=title;setText("#dndTitle",title);setText("#dndSubtitle",subtitle);setText("#whSubtitle",subtitle);
if(title.length>36)cinematic.classList.add("title-xlong");else if(title.length>24)cinematic.classList.add("title-long");
function buildSkulls(){const field=document.querySelector("#skullRain"),srcs=["/assets/mork-skull-1.png","/assets/mork-skull-2.png","/assets/mork-skull-3.png","/assets/mork-skull-4.png"];const count=10;for(let i=0;i<count;i++){const img=document.createElement("img");img.src=srcs[i%srcs.length];img.className=`falling-skull skull-${i%4}`;img.style.setProperty("--x",`${5+((i*17)%92)}vw`);img.style.setProperty("--size",`${110+((i*43)%180)}px`);img.style.setProperty("--delay",`${(i%5)*90}ms`);img.style.setProperty("--fall",`${900+((i*137)%650)}ms`);img.style.setProperty("--rot",`${-35+((i*29)%70)}deg`);if(i%4===3)img.classList.add("skull-green");field.append(img)}}
function buildWarhammerLetters(){const h=document.querySelector("#whTitle");h.textContent="";[...title].forEach((ch,i)=>{const s=document.createElement("span");s.className=ch===" "?"wh-space":"wh-letter";s.textContent=ch===" "?"\u00A0":ch;s.style.setProperty("--i",String(i));h.append(s)});const sparks=document.querySelector("#sparkField");const sparkCount=Math.min(14,Math.max(6,title.replaceAll(" ","").length));for(let i=0;i<sparkCount;i++){const s=document.createElement("i");s.style.setProperty("--sx",`${10+((i*37)%80)}%`);s.style.setProperty("--sy",`${35+((i*19)%30)}%`);s.style.setProperty("--sd",`${760+i*55}ms`);sparks.append(s)}}
if(theme==="morkborg")buildSkulls();if(theme==="warhammer")buildWarhammerLetters();
if(params.get("preview")==="1"){requestAnimationFrame(()=>document.body.classList.add("ready"))}else{OBR.onReady(()=>{requestAnimationFrame(()=>document.body.classList.add("ready"));setTimeout(()=>OBR.modal.close(MODAL_ID).catch(()=>{}),duration+260)})}
